/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TelemteryRouteImport } from './routes/telemtery'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as GarageCardIdRouteImport } from './routes/garage.$cardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemteryRoute = TelemteryRouteImport.update({
  id: '/telemtery',
  path: '/telemtery',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageCardIdRoute = GarageCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => GarageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/garage': typeof GarageRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/telemtery': typeof TelemteryRoute
  '/voice': typeof VoiceRoute
  '/garage/$cardId': typeof GarageCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/garage': typeof GarageRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/telemtery': typeof TelemteryRoute
  '/voice': typeof VoiceRoute
  '/garage/$cardId': typeof GarageCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/garage': typeof GarageRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/telemtery': typeof TelemteryRoute
  '/voice': typeof VoiceRoute
  '/garage/$cardId': typeof GarageCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/garage'
    | '/profile'
    | '/settings'
    | '/telemtery'
    | '/voice'
    | '/garage/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/garage'
    | '/profile'
    | '/settings'
    | '/telemtery'
    | '/voice'
    | '/garage/$cardId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/garage'
    | '/profile'
    | '/settings'
    | '/telemtery'
    | '/voice'
    | '/garage/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  GarageRoute: typeof GarageRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TelemteryRoute: typeof TelemteryRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemtery': {
      id: '/telemtery'
      path: '/telemtery'
      fullPath: '/telemtery'
      preLoaderRoute: typeof TelemteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/$cardId': {
      id: '/garage/$cardId'
      path: '/$cardId'
      fullPath: '/garage/$cardId'
      preLoaderRoute: typeof GarageCardIdRouteImport
      parentRoute: typeof GarageRoute
    }
  }
}

interface GarageRouteChildren {
  GarageCardIdRoute: typeof GarageCardIdRoute
}

const GarageRouteChildren: GarageRouteChildren = {
  GarageCardIdRoute: GarageCardIdRoute,
}

const GarageRouteWithChildren =
  GarageRoute._addFileChildren(GarageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  GarageRoute: GarageRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TelemteryRoute: TelemteryRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
