/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as TelemteryRouteImport } from './routes/telemtery'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as GarageIndexRouteImport } from './routes/garage.index'
import { Route as GarageCarIdRouteImport } from './routes/garage.$carId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemteryRoute = TelemteryRouteImport.update({
  id: '/telemtery',
  path: '/telemtery',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageIndexRoute = GarageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GarageRoute,
} as any)
const GarageCarIdRoute = GarageCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => GarageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/garage': typeof GarageRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/telemtery': typeof TelemteryRoute
  '/tracks': typeof TracksRoute
  '/voice': typeof VoiceRoute
  '/garage/$carId': typeof GarageCarIdRoute
  '/garage/': typeof GarageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/telemtery': typeof TelemteryRoute
  '/tracks': typeof TracksRoute
  '/voice': typeof VoiceRoute
  '/garage/$carId': typeof GarageCarIdRoute
  '/garage': typeof GarageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/garage': typeof GarageRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/profile': typeof ProfileRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
  '/telemtery': typeof TelemteryRoute
  '/tracks': typeof TracksRoute
  '/voice': typeof VoiceRoute
  '/garage/$carId': typeof GarageCarIdRoute
  '/garage/': typeof GarageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/garage'
    | '/knowledge'
    | '/profile'
    | '/sessions'
    | '/settings'
    | '/telemetry'
    | '/telemtery'
    | '/tracks'
    | '/voice'
    | '/garage/$carId'
    | '/garage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/knowledge'
    | '/profile'
    | '/sessions'
    | '/settings'
    | '/telemetry'
    | '/telemtery'
    | '/tracks'
    | '/voice'
    | '/garage/$carId'
    | '/garage'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/garage'
    | '/knowledge'
    | '/profile'
    | '/sessions'
    | '/settings'
    | '/telemetry'
    | '/telemtery'
    | '/tracks'
    | '/voice'
    | '/garage/$carId'
    | '/garage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  GarageRoute: typeof GarageRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRoute
  ProfileRoute: typeof ProfileRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  TelemetryRoute: typeof TelemetryRoute
  TelemteryRoute: typeof TelemteryRoute
  TracksRoute: typeof TracksRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemtery': {
      id: '/telemtery'
      path: '/telemtery'
      fullPath: '/telemtery'
      preLoaderRoute: typeof TelemteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/': {
      id: '/garage/'
      path: '/'
      fullPath: '/garage/'
      preLoaderRoute: typeof GarageIndexRouteImport
      parentRoute: typeof GarageRoute
    }
    '/garage/$carId': {
      id: '/garage/$carId'
      path: '/$carId'
      fullPath: '/garage/$carId'
      preLoaderRoute: typeof GarageCarIdRouteImport
      parentRoute: typeof GarageRoute
    }
  }
}

interface GarageRouteChildren {
  GarageCarIdRoute: typeof GarageCarIdRoute
  GarageIndexRoute: typeof GarageIndexRoute
}

const GarageRouteChildren: GarageRouteChildren = {
  GarageCarIdRoute: GarageCarIdRoute,
  GarageIndexRoute: GarageIndexRoute,
}

const GarageRouteWithChildren =
  GarageRoute._addFileChildren(GarageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  GarageRoute: GarageRouteWithChildren,
  KnowledgeRoute: KnowledgeRoute,
  ProfileRoute: ProfileRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  TelemetryRoute: TelemetryRoute,
  TelemteryRoute: TelemteryRoute,
  TracksRoute: TracksRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
